@namespace
class SpriteKind:
    swordcharacter = SpriteKind.create()
    ghost = SpriteKind.create()

def on_on_overlap(sprite5, otherSprite2):
    otherSprite2.destroy(effects.spray, 50)
    pause(300)
    info.change_life_by(-1)
    tiles.place_on_random_tile(Enemyevil, sprites.dungeon.floor_dark0)
sprites.on_overlap(SpriteKind.player, SpriteKind.enemy, on_on_overlap)

def checkScore():
    if info.score() >= 15:
        game.over(True)
    elif info.score() < 15:
        game.show_long_text("come back with 15 heads to leave", DialogLayout.BOTTOM)
        tiles.place_on_random_tile(mainCharacter, sprites.dungeon.stair_south)
        tiles.place_on_random_tile(swordmainCharacter, sprites.dungeon.stair_south)

def on_up_pressed():
    if Person == True:
        swordmainCharacter.set_image(swordcharacterImages[4 - 1])
    else:
        mainCharacter.set_image(noSwordplayerImages[4 - 1])
controller.up.on_event(ControllerButtonEvent.PRESSED, on_up_pressed)

def on_overlap_tile(sprite, location):
    global swordmainCharacter, swordcharacterImages, Person
    mainCharacter.destroy()
    sprites.destroy_all_sprites_of_kind(SpriteKind.enemy, effects.spray, 100)
    swordmainCharacter = sprites.create(img("""
            ......ffff..............
                    ....fff22fff............
                    ...fff2222fff...........
                    ..fffeeeeeefff..........
                    ..ffe222222eef..........
                    ..fe2ffffff2ef..........
                    ..ffffeeeeffff......ccc.
                    .ffefbf44fbfeff....cddc.
                    .ffefbf44fbfeff...cddc..
                    .fee4dddddd4eef.ccddc...
                    fdfeeddddd4eeffecddc....
                    fbffee4444ee4fddccc.....
                    fbf4f222222f1edde.......
                    fcf.f222222f44ee........
                    .ff.f445544f............
                    ....ffffffff............
                    .....ff..ff.............
                    ........................
                    ........................
                    ........................
                    ........................
                    ........................
                    ........................
                    ........................
        """),
        SpriteKind.swordcharacter)
    controller.move_sprite(swordmainCharacter)
    scene.camera_follow_sprite(swordmainCharacter)
    tiles.place_on_random_tile(swordmainCharacter, sprites.dungeon.door_locked_west)
    swordcharacterImages = [img("""
            ......ffff..............
                    ....fff22fff............
                    ...fff2222fff...........
                    ..fffeeeeeefff..........
                    ..ffe222222eef..........
                    ..fe2ffffff2ef..........
                    ..ffffeeeeffff......ccc.
                    .ffefbf44fbfeff....cddc.
                    .ffefbf44fbfeff...cddc..
                    .fee4dddddd4eef.ccddc...
                    fdfeeddddd4eeffecddc....
                    fbffee4444ee4fddccc.....
                    fbf4f222222f1edde.......
                    fcf.f222222f44ee........
                    .ff.f445544f............
                    ....ffffffff............
                    .....ff..ff.............
                    ........................
                    ........................
                    ........................
                    ........................
                    ........................
                    ........................
                    ........................
        """),
        img("""
            ........................
                    ....ffffff..............
                    ..ffeeeef2f.............
                    .ffeeeef222f............
                    .feeeffeeeef...cc.......
                    .ffffee2222ef.cdc.......
                    .fe222ffffe2fcddc.......
                    fffffffeeeffcddc........
                    ffe44ebf44ecddc.........
                    fee4d41fddecdc..........
                    .feee4dddedccc..........
                    ..ffee44e4dde...........
                    ...f222244ee............
                    ...f2222e2f.............
                    ...f444455f.............
                    ....ffffff..............
                    .....fff................
                    ........................
                    ........................
                    ........................
                    ........................
                    ........................
                    ........................
                    ........................
        """),
        img("""
            ..............ffffff....
                    .............f2feeeeff..
                    ............f222feeeeff.
                    .......cc...feeeeffeeef.
                    .......cdc.fe2222eeffff.
                    .......cddcf2effff222ef.
                    ........cddcffeeefffffff
                    .........cddce44fbe44eff
                    ..........cdceddf14d4eef
                    ..........cccdeddd4eeef.
                    ...........edd4e44eeff..
                    ............ee442222f...
                    .............f2e2222f...
                    .............f554444f...
                    ..............ffffff....
                    ................fff.....
                    ........................
                    ........................
                    ........................
                    ........................
                    ........................
                    ........................
                    ........................
                    ........................
        """),
        img("""
            . . . . . . f f f f . . . . . . 
                    . . . . f f e e e e f f . . . . 
                    . . . f e e e f f e e e f . . . 
                    . . f f f f f 2 2 f f f f f . . 
                    . . f f e 2 e 2 2 e 2 e f f . . 
                    . . f e 2 f 2 f f 2 f 2 e f . . 
                    . . f f f 2 2 e e 2 2 f f f . . 
                    . f f e f 2 f e e f 2 f e f f . 
                    . f e e f f e e e e f e e e f . 
                    . . f e e e e e e e e e e f . . 
                    . . . f e e e e e e e e f . . . 
                    . . e 4 f f f f f f f f 4 e . . 
                    . . 4 d f 2 2 2 2 2 2 f d 4 . . 
                    . . 4 4 f 4 4 4 4 4 4 f 4 4 . . 
                    . . . . . f f f f f f . . . . . 
                    . . . . . f f . . f f . . . . .
        """)]
    Person = True
scene.on_overlap_tile(SpriteKind.player,
    sprites.dungeon.door_locked_west,
    on_overlap_tile)

def on_left_pressed():
    if Person == True:
        swordmainCharacter.set_image(swordcharacterImages[3 - 1])
    else:
        mainCharacter.set_image(noSwordplayerImages[3 - 1])
controller.left.on_event(ControllerButtonEvent.PRESSED, on_left_pressed)

def on_on_overlap2(sprite2, otherSprite):
    if Person == True:
        otherSprite.destroy()
        pause(200)
        info.change_score_by(1)
    swordcharacterenemySetup(True)
sprites.on_overlap(SpriteKind.swordcharacter, SpriteKind.enemy, on_on_overlap2)

def on_overlap_tile2(sprite3, location2):
    checkScore()
scene.on_overlap_tile(SpriteKind.player,
    sprites.dungeon.purple_switch_down,
    on_overlap_tile2)

def swordcharacterenemySetup(bool2: bool):
    global Enemyevil
    Enemyevil = sprites.create(EnemieList._pick_random(), SpriteKind.enemy)
    tiles.place_on_random_tile(Enemyevil, sprites.dungeon.floor_dark0)

def on_right_pressed():
    if Person == True:
        swordmainCharacter.set_image(swordcharacterImages[2 - 1])
    else:
        mainCharacter.set_image(noSwordplayerImages[2 - 1])
controller.right.on_event(ControllerButtonEvent.PRESSED, on_right_pressed)

def gameSetup():
    global EnemieList, Enemyevil, Person
    setupPlayer()
    info.start_countdown(45)
    tiles.set_tilemap(tilemap("""
        level1
    """))
    scene.camera_follow_sprite(mainCharacter)
    tiles.place_on_random_tile(mainCharacter, sprites.dungeon.stair_south)
    EnemieList = [img("""
            ........................
                    ........................
                    ........................
                    ........................
                    ..........ffff..........
                    ........ff1111ff........
                    .......fb111111bf.......
                    .......f11111111f.......
                    ......fd11111111df......
                    ......fd11111111df......
                    ......fddd1111dddf......
                    ......fbdbfddfbdbf......
                    ......fcdcf11fcdcf......
                    .......fb111111bf.......
                    ......fffcdb1bdffff.....
                    ....fc111cbfbfc111cf....
                    ....f1b1b1ffff1b1b1f....
                    ....fbfbffffffbfbfbf....
                    .........ffffff.........
                    ...........fff..........
                    ........................
                    ........................
                    ........................
                    ........................
        """),
        img("""
            ........................
                    ........................
                    ........................
                    ........................
                    ........................
                    ..........ffff..........
                    ........ff1111ff........
                    .......fb111111bf.......
                    .....fffc1111111f.......
                    ...fc111cd1111111f......
                    ...f1b1b1b1111dddf......
                    ...fbfbffcf11fcddf......
                    ......fcf111111bbf......
                    .......ccbdb1b1fcf......
                    .......fffbfbfdff.......
                    ........ffffffff........
                    ........fffffffffff.....
                    .........fffffc111cf....
                    .........fffff1b1b1f....
                    ..........ffffbfbfbf....
                    ...........ffff.........
                    ........................
                    ........................
                    ........................
        """),
        img("""
            . . f f f . . . . . . . . . . . 
                    f f f c c . . . . . . . . f f f 
                    f f c c . . c c . . . f c b b c 
                    f f c 3 c c 3 c c f f b b b c . 
                    f f b 3 b c 3 b c f b b c c c . 
                    . c b b b b b b c f b c b c c . 
                    . c b b b b b b c b b c b b c . 
                    c b 1 b b b 1 b b b c c c b c . 
                    c b b b b b b b b c c c c c . . 
                    f b c b b b c b b b b f c . . . 
                    f b 1 f f f 1 b b b b f c c . . 
                    . f b b b b b b b b c f . . . . 
                    . . f b b b b b b c f . . . . . 
                    . . . f f f f f f f . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . .
        """),
        img("""
            ........................
                    ........................
                    ...........cc...........
                    ...........cccc.........
                    .......cc...ccccccc.....
                    .......cccccc555555cc...
                    ........ccb5555555555c..
                    .....cc..b555555555555c.
                    .....cccb555555ff155555c
                    .....ccb55555555ff55d55c
                    ......b5555555555555555c
                    ...c..b555d55555bb13bbc.
                    ...cccd55ddddd55bb3335c.
                    ....cbdddddddddd55b335c.
                    ..cccdddddb55bdddd5555c.
                    ..cccdddddb555bbbbcccc..
                    ...ccddddddb5555cbcdc...
                    ccccbdddddddcb55cbcc....
                    cddddddddd55dbccbbc.....
                    cbdddddddd555dbbbcc.....
                    .ccbdddbbdd555bbcdbcc...
                    ...cccbbbbdd55ccdddbc...
                    ......cccbdddbccccccc...
                    ........cdd555dc........
        """),
        img("""
            ...........fffffff...ccfff..........
                    ..........fbbbbbbbffcbbbbf..........
                    ..........fbb111bbbbbffbf...........
                    ..........fb11111ffbbbbff...........
                    ..........f1cccc1ffbbbbbcff.........
                    ..........ffc1c1c1bbcbcbcccf........
                    ...........fcc3331bbbcbcbcccf..ccccc
                    ............c333c1bbbcbcbccccfcddbbc
                    ............c333c1bbbbbbbcccccddbcc.
                    ............c333c11bbbbbccccccbbcc..
                    ...........cc331c11bbbbccccccfbccf..
                    ...........cc13c11cbbbcccccbbcfccf..
                    ...........c111111cbbbfdddddc.fbbcf.
                    ............cc1111fbdbbfdddc...fbbf.
                    ..............cccfffbdbbfcc.....fbbf
                    ....................fffff........fff
        """),
        img("""
            . . . . . c c c c c c c . . . . 
                    . . . . c 6 7 7 7 7 7 6 c . . . 
                    . . . c 7 c 6 6 6 6 c 7 6 c . . 
                    . . c 6 7 6 f 6 6 f 6 7 7 c . . 
                    . . c 7 7 7 7 7 7 7 7 7 7 c . . 
                    . . f 7 8 1 f f 1 6 7 7 7 f . . 
                    . . f 6 f 1 f f 1 f 7 7 7 f . . 
                    . . . f f 2 2 2 2 f 7 7 6 f . . 
                    . . c c f 2 2 2 2 7 7 6 f c . . 
                    . c 7 7 7 7 7 7 7 7 c c 7 7 c . 
                    c 7 1 1 1 7 7 7 7 f c 6 7 7 7 c 
                    f 1 1 1 1 1 7 6 f c c 6 6 6 c c 
                    f 1 1 1 1 1 1 6 6 c 6 6 6 c . . 
                    f 6 1 1 1 1 1 6 6 6 6 6 6 c . . 
                    . f 6 1 1 1 1 1 6 6 6 6 c . . . 
                    . . f f c c c c c c c c . . . .
        """)]
    Enemyevil = sprites.create(EnemieList._pick_random(), SpriteKind.enemy)
    Person = False
    while Person == False:
        Enemyevil = sprites.create(EnemieList._pick_random(), SpriteKind.enemy)
        tiles.place_on_random_tile(Enemyevil, sprites.dungeon.floor_dark0)
        pause(2000)
    if Person == True:
        Enemyevil = sprites.create(EnemieList._pick_random(), SpriteKind.enemy)
        tiles.place_on_random_tile(Enemyevil, sprites.dungeon.floor_dark0)

def on_down_pressed():
    if Person == True:
        swordmainCharacter.set_image(swordcharacterImages[1 - 1])
    else:
        mainCharacter.set_image(noSwordplayerImages[1 - 1])
controller.down.on_event(ControllerButtonEvent.PRESSED, on_down_pressed)

def setupPlayer():
    global mainCharacter, noSwordplayerImages
    mainCharacter = sprites.create(img("""
            . . . . . . f f f f . . . . . . 
                    . . . . f f f 2 2 f f f . . . . 
                    . . . f f f 2 2 2 2 f f f . . . 
                    . . f f f e e e e e e f f f . . 
                    . . f f e 2 2 2 2 2 2 e e f . . 
                    . . f e 2 f f f f f f 2 e f . . 
                    . . f f f f e e e e f f f f . . 
                    . f f e f b f 4 4 f b f e f f . 
                    . f e e 4 1 f d d f 1 4 e e f . 
                    . . f e e d d d d d d e e f . . 
                    . . . f e e 4 4 4 4 e e f . . . 
                    . . e 4 f 2 2 2 2 2 2 f 4 e . . 
                    . . 4 d f 2 2 2 2 2 2 f d 4 . . 
                    . . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
                    . . . . . f f f f f f . . . . . 
                    . . . . . f f . . f f . . . . .
        """),
        SpriteKind.player)
    info.set_life(3)
    info.set_score(0)
    noSwordplayerImages = [img("""
            . . . . . . f f f f . . . . . . 
                    . . . . f f f 2 2 f f f . . . . 
                    . . . f f f 2 2 2 2 f f f . . . 
                    . . f f f e e e e e e f f f . . 
                    . . f f e 2 2 2 2 2 2 e e f . . 
                    . . f e 2 f f f f f f 2 e f . . 
                    . . f f f f e e e e f f f f . . 
                    . f f e f b f 4 4 f b f e f f . 
                    . f e e 4 1 f d d f 1 4 e e f . 
                    . . f e e d d d d d d e e f . . 
                    . . . f e e 4 4 4 4 e e f . . . 
                    . . e 4 f 2 2 2 2 2 2 f 4 e . . 
                    . . 4 d f 2 2 2 2 2 2 f d 4 . . 
                    . . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
                    . . . . . f f f f f f . . . . . 
                    . . . . . f f . . f f . . . . .
        """),
        img("""
            . . . . . . . . . . . . . . . . 
                    . . . . . f f f f f f . . . . . 
                    . . . f f e e e e f 2 f . . . . 
                    . . f f e e e e f 2 2 2 f . . . 
                    . . f e e e f f e e e e f . . . 
                    . . f f f f e e 2 2 2 2 e f . . 
                    . . f e 2 2 2 f f f f e 2 f . . 
                    . f f f f f f f e e e f f f . . 
                    . f f e 4 4 e b f 4 4 e e f . . 
                    . f e e 4 d 4 1 f d d e f . . . 
                    . . f e e e e e d d d f . . . . 
                    . . . . f 4 d d e 4 e f . . . . 
                    . . . . f e d d e 2 2 f . . . . 
                    . . . f f f e e f 5 5 f f . . . 
                    . . . f f f f f f f f f f . . . 
                    . . . . f f . . . f f f . . . .
        """),
        img("""
            . . . . f f f f f f . . . . . . 
                    . . . f 2 f e e e e f f . . . . 
                    . . f 2 2 2 f e e e e f f . . . 
                    . . f e e e e f f e e e f . . . 
                    . f e 2 2 2 2 e e f f f f . . . 
                    . f 2 e f f f f 2 2 2 e f . . . 
                    . f f f e e e f f f f f f f . . 
                    . f e e 4 4 f b e 4 4 e f f . . 
                    . . f e d d f 1 4 d 4 e e f . . 
                    . . . f d d d d 4 e e e f . . . 
                    . . . f e 4 4 4 e e f f . . . . 
                    . . . f 2 2 2 e d d 4 . . . . . 
                    . . . f 2 2 2 e d d e . . . . . 
                    . . . f 5 5 4 f e e f . . . . . 
                    . . . . f f f f f f . . . . . . 
                    . . . . . . f f f . . . . . . .
        """),
        img("""
            . . . . . . f f f f . . . . . . 
                    . . . . f f e e e e f f . . . . 
                    . . . f e e e f f e e e f . . . 
                    . . f f f f f 2 2 f f f f f . . 
                    . . f f e 2 e 2 2 e 2 e f f . . 
                    . . f e 2 f 2 f f 2 f 2 e f . . 
                    . . f f f 2 2 e e 2 2 f f f . . 
                    . f f e f 2 f e e f 2 f e f f . 
                    . f e e f f e e e e f e e e f . 
                    . . f e e e e e e e e e e f . . 
                    . . . f e e e e e e e e f . . . 
                    . . e 4 f f f f f f f f 4 e . . 
                    . . 4 d f 2 2 2 2 2 2 f d 4 . . 
                    . . 4 4 f 4 4 4 4 4 4 f 4 4 . . 
                    . . . . . f f f f f f . . . . . 
                    . . . . . f f . . f f . . . . .
        """)]
    controller.move_sprite(mainCharacter)

def on_life_zero():
    game.over(False, effects.dissolve)
info.on_life_zero(on_life_zero)

def on_overlap_tile3(sprite4, location3):
    checkScore()
scene.on_overlap_tile(SpriteKind.swordcharacter,
    sprites.dungeon.purple_switch_down,
    on_overlap_tile3)

EnemieList: List[Image] = []
noSwordplayerImages: List[Image] = []
swordcharacterImages: List[Image] = []
Person = False
swordmainCharacter: Sprite = None
mainCharacter: Sprite = None
Enemyevil: Sprite = None
gameSetup()